---
title: "R install notes"
format: html
editor: visual
---

```{r, include=FALSE, eval=FALSE}

# remotes::dev_package_deps("yingtools2")
# yy <- remotes::package_deps("ggrepel")
# 
# library(GenomeInfoDbData)
# yy$package
# 
# yy %>% dt
# 
# pkgs <- installed.packages() %>% as_tibble()
# 
# setdiff(pkgs$Package,c(cran.pkgs,bioc.pkgs))
# xx=available.packages()
# package.dependencies(x, check = FALSE,
#                      depLevel = c("Depends", "Imports", "Suggests"))

```

## R installation

Windows: install: R, Rtools, RStudio, Git for Windows 

Ubuntu: install R (r-base, r-base-dev), Rstudio, default-jre, default-jdk, libcurl4-openssl-dev, git

macOS: install R, RStudio, JDK (x64)

```{bash}
#| eval: false

# update indices
sudo apt update -qq
# install two helper packages we need
sudo apt install --no-install-recommends software-properties-common dirmngr
# add the signing key (by Michael Rutter) for these repos
# To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 
# Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
# add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

sudo apt install --no-install-recommends r-base r-base-dev

sudo apt install default-jre default-jdk libcurl4-openssl-dev git

```



```{r}
#| eval: false

cran.pkgs <- c(
  "tidyverse",
  "rlang",
  "roxygen2",
  "remotes",
  "reticulate",
  "reshape2",
  "plyr",
  "xlsx",
  "formula.tools",
  "Hmisc",
  "ggrepel",
  "ggfittext",
  "BiocManager",
  "rbenchmark",
  "tictoc",
  "cmprsk",
  "DT",
  "shiny",
  "RJDBC",
  "shinycssloaders",
  "shinyvalidate",
  "ggiraph",
  "rjson",
  "usethis",
  "pingr",
  "styler",
  "logistf",
  "coxphf",
  "Rtsne",
  "umap"
)
install.packages(cran.pkgs)

bioc.pkgs <- c(
  "dada2",
  "seqinr",
  "phyloseq",
  "ggtree",
  "msa",
  "phytools",
  "DECIPHER",
  "phangorn"
)
BiocManager::install(bioc.pkgs)

remotes::install_github("ying14/yingtools2")
remotes::install_github("csgillespie/roxygen2Comment")

# remotes::install_git("https://github.mskcc.org/taury/ytrecipes.git")
# remotes::install_git("https://github.mskcc.org/taury/ytdata.git")
# remotes::install_git("https://github.mskcc.org/taury/ytpipeline.git")



# git clone https://github.com/ying14/yingtools2
# git clone https://github.mskcc.org/taury/ytrecipes
# git clone https://github.mskcc.org/taury/ytdata
# git clone https://github.mskcc.org/taury/ytpipeline

```

Install Miniconda for R

```{r}

reticulate::py_config()

```
