---
title: Linux Commands
description: Useful Linux terminal commands
format: html
categories: [terminal, linux]
toc: true
toc-depth: 6
toc-location: left
editor: source
---





## Find files:

##### Find files with specific pattern:

``` sh
find . -iname '*.pdf*'
```

::: column-margin
Use `-iname` for case-insensitive, `-name` for case sensitive
:::

##### Find files with regex pattern

``` sh
find . -iregex '.*800.*oligos'
```

::: column-margin
Note that this matches the *entire* filepath. Use `-iregex` for case-insensitive, `-regex` for case sensitive.
:::

Alternatively, do a pipe to `grep` to do partial matching:

``` sh
find . | grep -i '800.*oligos*'
```

::: column-margin
`-i` makes it case insensitive
:::

##### Find files with specific text

``` sh
find .  -name '*.txt*' -print0 | xargs -0 grep 'something'

find . -name '*.txt*' -exec grep -i 'something' {} \; 
# case insensitive
```

##### Search for '`keyword`' and show 2 lines before and after.

``` sh
grep -C 2 'keyword' file.txt
```

##### Search for file and show file datetime

find . -name "\*.f" -exec grep -nHo the_string {} ;

``` sh
find . -name '*json*' -printf "%-25p %t\n"
```

##### Find several file patterns, separated by `-o`

``` sh
find -type f \( -name 'reads?.fastq' -o -name 'barcodes.fastq' \)
```

##### Find files and sum up file size

``` sh
find -type f -iname '*.fastq.gz' -exec du {} + | awk '{ total += $1 }; END { print total/1023/1023,"Gb" }' 
```

##### Find files and delete

``` sh
find -type f -iname '*.fastq.gz' -delete
```

##### Find files and copy recursively. Will create all the dirs necessary.

``` sh
find . -name '*.txt' | cpio -pdm /path

# this also works but is a little wonky
find . -name '*.mp3' -exec cp {} /path \;
```

##### Find directories one level deep

``` sh
find .-type d -maxdepth 1
```

##### List disk mounts

``` sh
mount -l
lsblk
```

## Disk usage

##### Find largest file in directory (`-a` lists file sizes)

``` sh
du -a /dir/ | sort -n -r | head -n 20
```

``` sh
sudo du -hx | sort -hr | head -n 20
# du -h
# du -k -d1 * | sort -nr | cut -f2 | xargs -d '\n' du -sh
```

Remove tmp files to make space on root

``` sh
sudo find /tmp -type f -atime +10 -delete

sudo find /tmp -type f -atime +10 -exec du {} + | awk '{ total += $1 }; END { print total/1023/1023,"Gb" }' 

# du -h
# du -k -d1 * | sort -nr | cut -f2 | xargs -d '\n' du -sh
```

## X2GO commands

List sessions

``` sh
x2golistsessions
```

``` 47409|ying-50-1666546387_stdkde_dp32|50|iski0021|r|2022-10-23t13:33:07|eccbae477812d21a69840bf3a59515a1|10.252.13.86|39201|39202|2022-10-31t10:30:30|ying|680416|39203|-1|-1
ying@iski0021[ying] 47409|ying-50-1666546387_stDKDE_dp32|50|iski0021|R|2022-10-23T13:33:07|eccbae477812d21a69840bf3a59515a1|10.252.13.86|39201|39202|2022-10-31T10:30:30|ying|680416|39203|-1|-1
```

Field 1 `47409` is agent ID Field 2 `ying-50-1666546387_stDKDE_dp32` is session ID.

Terminate session

``` sh
x2goterminate-session <sessio_ID>
```
